// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtklaelvnvDx6tkU4eR4bY9GNSq9tjU8',
    appId: '1:802579808080:web:6806d9de3eb77030047655',
    messagingSenderId: '802579808080',
    projectId: 'store-bydevorder',
    authDomain: 'store-bydevorder.firebaseapp.com',
    storageBucket: 'store-bydevorder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZqzmpVm1DaAwFnW18Co7CU7JFbXBGjO4',
    appId: '1:802579808080:android:d3efc95bfa3122df047655',
    messagingSenderId: '802579808080',
    projectId: 'store-bydevorder',
    storageBucket: 'store-bydevorder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQshNAgx1w-2rtX6VHk2bhqTrvORB8Rg',
    appId: '1:802579808080:ios:381f5167070dfc27047655',
    messagingSenderId: '802579808080',
    projectId: 'store-bydevorder',
    storageBucket: 'store-bydevorder.appspot.com',
    iosClientId: '802579808080-r0oaslo18rddgmi6kbee0e1flj1st7k7.apps.googleusercontent.com',
    iosBundleId: 'com.bydevorder.storeAdmin',
  );
}
